#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-TW-TSEQuote
version:      0.2
version_from: TSEQuote.pm
installdirs:  site
requires:
    URI::Escape:                   0
    LWP::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_06
