# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-TW-TSEQuote
version:      0.27
version_from: lib/Finance/TW/TSEQuote.pm
installdirs:  site
requires:
    LWP::Simple:                   0
    URI::Escape:                   0

distribution_type: module
generated_by: FUCK WHY I HAVE TO MANUALLY UPDATE THIS 1.0
